name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get version
        id: ara_version
        run: |
          version=$(grep ara requirements.txt | cut -d'=' -f3)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tigattack/ara
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ steps.ara_version.outputs.version }}
            type=semver,pattern={{major.minor}},value=${{ steps.ara_version.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.ara_version.outputs.version }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'workflow_dispatch' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
